$(function(){		
    //验证用户名是否存在
    $("#username").blur(function(){
        $.get(
            "checkUser.php",
            {
                "username":$("#username").val()	
            },
            function(data){
                if(data=="1"){
                    $("#showUser").html("√");	
                    $("#showUser").css({
                        'color':'#0f0'
                    })					
                }else{
                    $("#showUser").html("×");
                    $("#showUser").css({
                        'color':'red'
                    })
                }
            }				
        );		
    });
    $("#btnReg").click(function(){
        //1、
        $.post(
            "addUser.php",
            {
                "username":$("#username").val()	,
                "userPass":$("#userpass").val()
            },
            function(data){					
                if(data=="success"){
                    $("#messageBox").html("注册成功");
                    $("#messageBox").css({
                        'color':'#0f0'
                    })
                    setTimeout(()=>{						
                        location.href="login.html";	
                    },3000);
                }else{
                    $("#messageBox").html("注册失败！");
                    $("#messageBox").css({
                        'color':'red'
                    })
                }
            }
        );
    });
});